name: Flutter CI

on:
  push:
    branches:
      - '**'        # matches every branch

jobs:
  frontend-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        include:
          - os: macos-latest
            flutter_path: /Users/runner/hostedtoolcache/flutter
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

  frontend-android-integration-test:
    needs: frontend-setup
    name: run integration test on Android emulator
    runs-on: macos-latest
    strategy:
      matrix:
        device:
          - "pixel"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      
    # Cache Flutter Environment
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v3
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Launch Tests and screenshots
      - name: run tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: ${{ matrix.device }}
          target: google_apis
          script: | 
            ./scripts/run_tests.sh integration_test/tests -d "emulator-5554"
          
  frontend-ios-integration-test:
    needs: frontend-setup
    #Create a construction matrix
    strategy:
      #Set up different configurations for a set of virtual environments
      matrix:
        device:
          - "iPhone 8 Simulator"
      #When set to true, GitHub cancels all in progress jobs if any of the matrix jobs fail.
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      # Start Emulator
      - name: "List all simulators"
        run: "xcrun xctrace list devices"
      - name: "Start Simulator"
        run: |
          UDID=$(xcrun xctrace list devices | grep "^${{ matrix.device }}" | awk '{gsub(/[()]/,""); print $NF}')
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"

      # Cache Flutter Environment
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v3
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Launch tests
      - name: "Run Flutter Driver tests"
        run: |
          ./scripts/run_tests.sh integration_test/tests
